# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original file is located at
https://colab.research.google.com/drive/1ANWX-dcFCxxGtUT8uPWqcPbtzobjUcZ6

### **TWITTER STOCK MARKET**

Twitter a été fondé en 2006 et a été coté en bourse en 2013. Depuis la fondation de Twitter, l'année 2022 a été un événement mémorable pour Twitter. Lorsque Elon Musk a pris le contrôle de Twitter, il a été retiré de la Bourse de New York. Comme 2022 a été si mouvementée pour Twitter, analysons la chronologie complète de Twitter sur le marché boursier de 2013 à 2022.

Twitter est l'une des applications de médias sociaux populaires où les gens partagent ce qu'ils ressentent en un nombre limité de mots. Twitter est populaire, mais pas en bourse.

La data contient :

Date

The opening Price of the day

The highest price of the day

The lowest price of the day

The closing price of the day

The adjusted closing price of the day

The total number of shares traded in the day (volume)

L'objectif de ce projet est d'analyser la performance de Twitter sur le marché boursier au cours de la période de 2013 à 2022, et de prédire en mettant en évidence les événements clés de cette période.
"""
import joblib
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

# Load Dataset
df = pd.read_csv('Twitter Stock Market Dataset.csv')

# Display basic information about the dataset
print(df.info())

# Show the shape of the dataset
print(df.shape)

# Check for null values
print(df.isnull().sum())

# Remove null values
df = df.dropna()

# Twitter Stock Prices Over the Years
figure = go.Figure(data=[go.Candlestick(x=df["Date"],
                                        open=df["Open"],
                                        high=df["High"],
                                        low=df["Low"],
                                        close=df["Close"])])
figure.update_layout(title="Twitter Stock Prices Over the Years",
                     xaxis_rangeslider_visible=False)
figure.show()

# Visualize stock prices with a bar chart
figure = px.bar(df, x="Date", y="Close")
figure.update_traces(marker=dict(color='blue'))
figure.update_xaxes(rangeslider_visible=True)
figure.show()

# Split data into Input and Output
df["Date"] = pd.to_datetime(df["Date"], format='%Y-%m-%d')
y = np.array(df["Close"])
X = np.array(df.drop(["Date", "Close", "Adj Close"], axis=1))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

# Regression Model
from sklearn.linear_model import LinearRegression

# Create a Linear Regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Predict
Y_pred = model.predict(X_test)

# Display predictions and original values
prediction_df = pd.DataFrame({'Predicted': Y_pred, 'Original': y_test})
print(prediction_df)

# Calculate and display the R-squared score
reg = LinearRegression()
reg.fit(X_train, y_train)
print("R-squared score:", reg.score(X_test, y_test))

joblib.dump(model , "TwitterstockMarket.joblib")